name: publish-shared-ui

on:
  push:
    branches:
      - "main"

permissions: write-all

jobs:
  build:
    name: publish-shared-ui-${{ github.run_number }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      GH_PAT: ${{ secrets.PAT_NO_EXP }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          token: ${{ env.GH_PAT }}

      - name: Automated Version Bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          minor-wording: "add,Adds,new,MINOR,minor,MIN,min"
          major-wording: "MAJOR,cut-major,MAJ,major,maj"
          patch-wording: "patch,fixes,bump" # defaults to patch!
          rc-wording: "RELEASE,alpha"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
          bump-policy: "ignore"
          tag-prefix: "v"

      - name: Npm Install & Publish
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: "https://npm.pkg.github.com"
          scope: "@infini-uiinc"
      - run: npm install # we have to install first because we bumped the version above
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
