name: Create Release

on:
  workflow_run:
    workflows: ["publish-shared-ui"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    name: Generate Release notes
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get previous version tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v

      - name: create release and auto generate notes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_NO_EXP }}
          TAG: ${{ steps.previoustag.outputs.tag }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} $TAG" \
              --generate-notes
